print("是星期一呀",end="")
print("哈哈哈哈",end="")
print(2333,end="")
print(2.333)
print(True,False)
print(None)
print(())
print([])
print({})
print("哈哈",2333,"你好")
print("哈哈"+"嘻嘻")
print("哈哈"*20)
print(1+1)
print(1+5*2/(2+4))
print(10%3)
print(1<3)
print(1==2 or 1<3)
print("色即是空空即是色")
name = "张三"
print(name)
res = (1+2+3+4+5*2/(4*2))%3
print(res)
a=input("请输入:")
print("这是我刚刚输入的值：",a)
b=input("请输入:")
"""
a = len("哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈")
print(a)
"""
print("0:表示偶数；1：表示奇数：")
lstr = input("请输入你要计算的内容：")
print(len(lstr)%2)